version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
    restart: always

  worker:
    build: .
    command: celery -A app.tasks.celery worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    restart: always
